language: node_js

node_js:
  - "9.2"

addons:
  apt:
    packages:
      - oracle-java8-installer

before_script:
  - npm install -g @angular/cli

script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B
  - cd webui && npm install && npm run test